import Head from "next/head";
import Header from "../header";
import Footer from "../Footer";
import styles from "./Layout.module.css";

// for typescript:
// import { ReactNode } from "react";
// interface LayoutProps {
//   children: ReactNode;
// }

export default function Layout(props) {
  const { children } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.content}>{children}</div>
      <Footer />
    </div>
  );
}
