import Head from "next/head";

const helloworld = () => {
  return (
    <div>
      <Head>
        {/* for title */}
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello World!</h1>;
    </div>
  );
};

export default helloworld;
