import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/header";
import styles from "../styles/Home.module.css";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <h1 className={styles.title}>welcome, kyra!</h1>
      <Footer />
    </div>
  );
}
