import Head from "next/head";
import Header from "../components/header";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <h1>welcome, kyra!</h1>
      </main>
    </div>
  );
}
